apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: my-grafana
  namespace: my-grafana
spec:
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: admin
      admin_user: admin
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  dataStorage:
    labels: # Additional labels for the PVC
      app: grafana
    annotations: # Additional annotations for the PVC
      app: grafana
    accessModes: # An array of access modes, e.g. `ReadWriteOnce`
    - ReadWriteMany
    size: '10Gi'        # Requested size, e.g. `10Gi`
    class: "nfs-client" 
  ingress:
    enabled: true
    hostname: my-grafana.apps-crc.testing

