apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-prometheus-external-service
  namespace: external-service
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      external-app-monitor: "true"
